title: 인액터스 성균관(Enactus SKK)
# url: "https://enactus-skk.org/"
url: 'https://enactus-skk.org'
baseurl:
google_analytics_key: 'UA-124494032-1'
google_maps_javascript_api_key:
site_verification:
  naver: 'b16b04b7844cbfe72dc8a0aae45d23ef9fc5c4b6'
facebook:
  app_id: '2058376827757026'
disqus_shortname:

locale: 'ko_KR'

# Default description in social shares for the jekyll-seo-tag gem
description: |
  A HEAD FOR BUSINESS. A HEART FOR THE WORLD.
  성균관 인액터스는 기업가정신의 실천을 통해 더 나은 사회를 만들어가는 사회혁신 경영학회입니다.
  우리는 비즈니스의 긍정적인 힘으로 세상에 변화를 가져오고 있습니다.

# Author details for the jekyll-seo-tag gem
author:
  name: Enactus SKK
  email: mail@enactus-skk.org
  twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Enactus SKK
  links:
    - https://enactus-skk.org

timezone: Asia/Seoul

collections:
  who_we_are:
    output: true
  what_we_do:
    output: true
  projects:
    output: true

paginate: 5
paginate_path: "/blog/:num/"
permalink: /:categories/:slug/
excerpt_separator: ""

  #<!--more-->
#pretty

jekyll-archives:
  enabled:
    - "categories"
  permalinks:
    category: '/:name/'

plugins:
  # https://github.com/jekyll/jekyll-feed
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"
#  - "jekyll-minifier"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - CNAME
  - _작업파일

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      sitemap: true
      layout: "post"
      is_post: true
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "projects"
    values:
      sitemap: true
      layout: "project"
      is_post: true
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "pages"
    values:
      sitemap: true
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      sitemap: true
      layout: "default"


feed:
  path: atom.xml

# -----------
# CloudCannon
# jekyll-seo-tag/usage.md at master · jekyll/jekyll-seo-tag
social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

# Exclude files from processing - file name, glob pattern or array of file names and glob patterns
#jekyll-minifier:
#  exclude:
#    - 'atom.xml'
#    - 'sitemap.xml'
#    - 'sitemap.xsl'
