[[redirects]]
  from = "https://enactus-skk.netlify.com/*"
  to = "https://enactus-skk.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://enactus-skk.netlify.com/*"
  to = "http://enactus-skk.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://enactus-skk.org/*"
  to = "https://enactus-skk.org/:splat"
  status = 301
  force = true

  [[redirects]]
    from = "/what-we-do/*"
    to = "https://enactus-skk.org/what-we-do#:splat"
    status = 200
    force = true
