[[redirects]]
  from = "https://enactus-skk.org.netlify.com/*"
  to = "https://www.enactus-skk.org.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://enactus-skk.org.netlify.com/*"
  to = "http://www.enactus-skk.org.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.enactus-skk.org.com/*"
  to = "https://www.enactus-skk.org.com/:splat"
  status = 301
  force = true
